#!/bin/sh
set -e

if ! find ./ -mindepth 1 -maxdepth 1 -name '*.cabal' -exec true ';'; then
  echo 'Unexpected: no cabal file.'
  exit 1
fi

if [ ! -f cabal.sandbox.config ]; then
  echo 'Unexpected: no sandbox.'
  exit 1
fi

if [ -e www.new -o -e www.old ]; then
  echo 'Unexpected: www.new or www.old exists.'
  exit 1
fi

SANDBOX="$(grep '^\s*prefix:' cabal.sandbox.config | awk '{print $2}')"
DB="$(find "$SANDBOX" -mindepth 1 -maxdepth 1 -type d -name '*-packages.conf.d')"
N_DBS="$(echo "$DB" | wc -l)"

if [ "$N_DBS" -ge 2 ]; then
  echo 'Unexpected: multiple package databases in sandbox.'
elif [ "$N_DBS" -eq 0 ]; then
  echo 'Unexpected: no package databases.'
fi

if [ -e www -a ! -d www ]; then
  echo 'Unexpected: www exists and is not a directory.'
  exit 1
fi

mkdir www.new
standalone-haddock --hyperlink-source --package-db "$DB" -o www.new .

if [ -d www ]; then
  mv www www.old
  mv www.new www
  rm -rf www.old
else
  mv www.new www
fi

